export default {
    data(){
        return {
            platformEnum1:[
                {
                    msgCode:"00401",
                    msgtype:10001,
                    router:"",
                    tip:"用户下单成功并支付，提示平台发货"
                },
                {
                    msgCode:"00402",
                    msgtype:10002,
                    router:"",
                    tip:"用户发起退款申请，提示平台进行确认，附带退款单号"
                },
                {
                    msgCode:"00403",
                    msgtype:10003,
                    router:"",
                    tip:"用户发起取消订单，提示平台"
                },
                {
                    msgCode:"00404",
                    msgtype:10004,
                    router:"",
                    tip:"用户填写回寄的物流信息后，提示平台进行确认，附带退款单号"
                },
                {
                    msgCode:"00405",
                    msgtype:10005,
                    router:"",
                    tip:"用户确认收货。提示进行评价"
                },
                {
                    msgCode:"00406",
                    msgtype:10006,
                    router:"",
                    tip:"用户取消支付"
                },
            ],
            platformEnum2:[
                {
                    msgCode:"00701",
                    msgtype:20001,
                    router:"",
                    tip:"用户下单后，提示商家接单"
                },
                {
                    msgCode:"00702",
                    msgtype:20002,
                    router:"",
                    tip:"用户付款后，外卖类需要提示商家备货"
                },
                {
                    msgCode:"00703",
                    msgtype:20003,
                    router:"",
                    tip:"纯服务类，到达预定时间，因用户未到店关闭订单的，提示用户"
                },
                {
                    msgCode:"00704",
                    msgtype:20004,
                    router:"",
                    tip:"用户发起加购订单，提示商户进行接单"
                },
                {
                    msgCode:"00705",
                    msgtype:20005,
                    router:"",
                    tip:"用户发起取消/退款订单申请，提示商户进行确认"
                },
                {
                    msgCode:"00706",
                    msgtype:20006,
                    router:"",
                    tip:"加购场景，用户发起加购付款，提示商户确认"
                },
                {
                    msgCode:"00707",
                    msgtype:20007,
                    router:"",
                    tip:"用户付款成功，提示商户已付款"
                },
                {
                    msgCode:"00708",
                    msgtype:20008,
                    router:"",
                    tip:"用户删除加购订单，需提示商户,附带原因"
                },
                {
                    msgCode:"00709",
                    msgtype:20009,
                    router:"",
                    tip:"用户取消加购订单，需提示商户,附带原因"
                },
                {
                    msgCode:"00710",
                    msgtype:20010,
                    router:"",
                    tip:"用户发起退款加购订单，需提示商户,附带原因"
                },
                {
                    msgCode:"00731",
                    msgtype:20031,
                    router:"",
                    tip:"商家接单时，若修改了订单信息，需提示用户"
                },
                {
                    msgCode:"00732",
                    msgtype:20032,
                    router:"",
                    tip:"商户拒绝接单，提示用户，并附带原因"
                },
                {
                    msgCode:"00733",
                    msgtype:20033,
                    router:"",
                    tip:"商家接单后，需要付款的订单，提示用户付款"
                },
                {
                    msgCode:"00734",
                    msgtype:20034,
                    router:"",
                    tip:"若商家拒绝接加购单，提示用户，并附带拒绝原因"
                },
                {
                    msgCode:"00735",
                    msgtype:20035,
                    router:"",
                    tip:"商户同意退款/取消申请，发送消息提示用户"
                },
                {
                    msgCode:"00736",
                    msgtype:20036,
                    router:"",
                    tip:"商户拒绝退款/取消申请，提示用户并附带拒绝原因"
                },
                {
                    msgCode:"00737",
                    msgtype:20037,
                    router:"",
                    tip:"外卖类，商家已发货，提示用户"
                },
                {
                    msgCode:"00738",
                    msgtype:20038,
                    router:"",
                    tip:"加购场景，商户确认用户发起的付款，提示用户进行付款"
                },
                {
                    msgCode:"00739",
                    msgtype:20039,
                    router:"",
                    tip:"商户同意用户加购的售后申请，提示用户"
                },
                {
                    msgCode:"00740",
                    msgtype:20040,
                    router:"",
                    tip:"商户拒绝用户加购的售后申请，提示用户，附带原因"
                },
                {
                    msgCode:"00741",
                    msgtype:20041,
                    router:"",
                    tip:"可加购场景，若商户加购用户的订单（排除线下下单），需提示用户"
                },
                {
                    msgCode:"00742",
                    msgtype:20042,
                    router:"",
                    tip:"用户发起付款，商家进行确认，并修改了金额，需提示用户"
                },
                {
                    msgCode:"00743",
                    msgtype:20043,
                    router:"",
                    tip:"商户删除加购订单，需提示用户,附带原因"
                },
                {
                    msgCode:"00744",
                    msgtype:20044,
                    router:"",
                    tip:"商户取消订单，需提示用户,附带原因"
                },
                {
                    msgCode:"00745",
                    msgtype:20045,
                    router:"",
                    tip:"商户确认用户到店消费"
                },
            ],
            platformEnum3:[
                {
                    msgCode:"00501",
                    msgtype:30001,
                    router:"",
                    tip:"用户分享成功，提示平台发货，并附带订单号"
                },
                {
                    msgCode:"00502",
                    msgtype:30002,
                    router:"",
                    tip:"用户填写回寄的物流信息后，提示平台，附带物流单号"
                },
                {
                    msgCode:"00503",
                    msgtype:30003,
                    router:"",
                    tip:"平台已发货，提示用户已发货，并附带物流单号"
                },
                {
                    msgCode:"00504",
                    msgtype:30004,
                    router:"",
                    tip:"平台同意报损申请，提示用户进行回寄操作"
                },
                {
                    msgCode:"00505",
                    msgtype:30005,
                    router:"",
                    tip:"平台拒绝用户的报损申请，提示用户，附带拒绝原因"
                },
                {
                    msgCode:"00506",
                    msgtype:30006,
                    router:"",
                    tip:"平台确认收货。提示进行评价"
                },
                {
                    msgCode:"00507",
                    msgtype:30007,
                    router:"",
                    tip:"用户提醒平台发货"
                },
                {
                    msgCode:"00508",
                    msgtype:30008,
                    router:"",
                    tip:"用户晒单提醒平台审核"
                },
                {
                    msgCode:"00509",
                    msgtype:30009,
                    router:"",
                    tip:"中奖提醒用户"
                },
                {
                    msgCode:"00510",
                    msgtype:30010,
                    router:"",
                    tip:"未中奖提醒用户"
                },
            ],
            platformEnum4:[
                {
                    msgCode:"00101",
                    msgtype:40001,
                    router:"",
                    tip:"您有一张xx优惠券即将过期，去查看"
                },
                {
                    msgCode:"00102",
                    msgtype:40002,
                    router:"",
                    tip:"用户创建店铺成功"
                },
                {
                    msgCode:"00103",
                    msgtype:40003,
                    router:"",
                    tip:"用户实名认证失败"
                },
            ],
            platformEnum5:[

            ],
        }
    },
    methods: {
        
    },
}